name: Clippy CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build test image
      run: |
        docker build -t clippy:test .
    
    - name: Test Docker build
      run: |
        docker run --rm clippy:test python -c "import flask; print('Flask imported successfully')"
        docker run --rm clippy:test python -c "import whisper; print('Whisper imported successfully')"
        docker run --rm clippy:test python -c "import cv2; print('OpenCV imported successfully')"
    
    - name: Check file structure
      run: |
        docker run --rm clippy:test ls -la /app

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run basic security checks
      run: |
        # Check for common security issues
        echo "Checking for hardcoded secrets..."
        ! grep -r "password.*=" --include="*.py" . || echo "Warning: Found potential hardcoded passwords"
        ! grep -r "api_key.*=" --include="*.py" . || echo "Warning: Found potential hardcoded API keys"